### DISCUSSION TITLE
feat: ✨ Expose color tokens as rgb values

### DISCUSSION THREAD

**Discussion by xkabylgSICKAG** [synergy-design-system/synergy-design-system#525] [RFCs]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a developer using the Synergy Design System, I want to have direct access to RGB color values for elements so that I can easily adjust opacity and create more flexible hover effects.

* **Context:** When implementing hover effects for some UI components, such as navigation items, I need to control the opacity of the background color.
* **Problem Statement:** Currently, the Synergy Design System provides predefined color variables (e.g. `--syn-color-neutral-600`), but these are not directly accessible in RGB format.
* **Solution:** By exposing RGB color values (e.g. `--syn-color-neutral-600-rgb: 133, 146, 152`), I can achieve consistent and customizable hover effects.
* **Business Value:**
   * **Improved Aesthetics:** Consistent hover effects enhance the overall visual appeal of our application.
   * **Efficiency:** Direct access to RGB values simplifies implementation and maintenance.
   * **Flexibility:** Developers can adjust opacity as needed for different use cases.

## Example

```css
/*
 * I would like for this css custom property (or one with another name but
 * containing the same value) to be available
 */
--syn-color-neutral-600-rgb: 133, 146, 152;

.cls:hover {
    background-color: rgba(var(--syn-color-neutral-600-rgb), 0.11);
}
```

## Current workaround
It's possible to use a psuedo-element and `opacity` to accomplish the same thing, in a lot more code:
```css
.cls {
  position: relative;
}
.cls::after {
  content: '';
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: -1;
  background-color: var(--syn-color-neutral-600);
  opacity: 0;
}
.cls:hover::after {
  opacity: 0.11;
} 
```

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] All current synergy color tokens exposed as css custom properties containing rgb values
