### ISSUE TITLE
fix: 🤔 Syn-radio uses wrong line-height when in multi-line mode

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#474]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 1.17.0 (probably since beginning)

# Component

The issue arises when using the following component(s): `<syn-radio />` 

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): all

# Description

Our radio component uses a fixed line-height for the label that matches the height of the item. This leads to an error when using multi line labels, where the font-size and line-height are set the same per default (e.g. font-size: 16px; line-height: 16px. This results in broken typographic styles.
See attached image:
![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/8658879a-440f-4b25-b82b-92359ae1f44c)

For the fix of this issue see the fix of the checkbox bug #456  or just use this: 

```css
  .radio__label {
    line-height: var(--syn-line-height-normal);
    position: relative;
  }

  .radio--small .radio__label {
    top: -3px;
  }

  .radio--medium .radio__label {
    top: -3px;
  }

  .radio--large .radio__label {
    top: -2px;
  }
  ```

The line-height which should be used has to be defined by design.

Radio is using the semantic [typography tokens](https://www.figma.com/design/bZFqk9urD3NlghGUKrkKCR/Synergy-Digital-Design-System?node-id=4415-2387&t=FIjL2Rk3xunkBYLQ-11)
     - small: Uses the text-style of `body/small/regular`
     - medium: Uses the text-style of `body/medium/regular`
     - large: Uses the text-style of `body/large/regular`

# Acceptance criteria

- [ ] All DoD items successfully completed

- [ ] Single line radios work like before
- [ ] multi line checkboxes have spacing between the text lines.
